[speed-minimum]
profile-desc=Clamp playback speed to 0.1x
profile-cond=p.speed and p.speed < 0.1
speed=0.1

[speed-maximum]
profile-desc=Clamp playback speed to 8x
profile-cond=p.speed and p.speed > 8
speed=8

[adaptive-video-sync]
profile-desc=Avoid costly interpolation for high frame rates or non-1x playback
profile-cond=p.container_fps and p.container_fps > 0 and (p.container_fps > 32 or (p.display_fps and p.display_fps / p.container_fps > 3.2) or (p.speed and p.speed ~= 1))
profile-restore=copy
interpolation=no
video-sync=audio

[hdr-content]
profile-desc=Subtitle composition suitable for HDR content
profile-cond=p["video-params/sig-peak"] and p["video-params/sig-peak"] > 1
profile-restore=copy
blend-subtitles=no
